columns:
  Total_Stops: float64
  Price: float64
  Journey_day: float64
  Journey_month: float64
  Dep_hour: float64
  Dep_min: float64
  Arrival_hour: float64
  Arrival_min: float64
  Duration_hours: float64
  Duration_mins: float64
  Airline_Air India: float64
  Airline_GoAir: float64
  Airline_IndiGo: float64
  Airline_Jet Airways: float64
  Airline_Jet Airways Business: float64
  Airline_Multiple carriers: float64
  Airline_Multiple carriers Premium economy: float64
  Airline_SpiceJet: float64
  Airline_Trujet: float64
  Airline_Vistara: float64
  Airline_Vistara: float64
  Source_Chennai: float64
  Source_Delhi: float64
  Source_Kolkata: float64
  Source_Mumbai: float64
  Destination_Cochin: float64
  Destination_Delhi: float64
  Destination_Hyderabad: float64
  Destination_Kolkata: float64
  Destination_New Delhi: float64
  
target_column: Price




