columns:
  Airline: category
  Source: category
  Destination: category
  Total_Stops: float
  Journey_day: float
  Journey_month: float
  Dep_hour: float
  Dep_min: float
  Arrival_hour: float
  Arrival_min: float
  Duration_hours: float
  Duration_mins: float
  Price: float



target_column: Price

numerical_columns:
  - Total_Stops
  - Journey_day
  - Journey_month
  - Dep_hour
  - Dep_min
  - Arrival_hour
  - Arrival_min
  - Duration_hours
  - Duration_mins

categorical_columns:
  - Airline
  - Source
  - Destination





domain_value:
  Airline:
    - Jet Airways 
    - IndiGo
    - Air India 
    - Multiple carriers
    - SpiceJet
    - Vistara
    - Air Asia
    - GoAir
    - Multiple carriers Premium economy
    - Jet Airways Business
    - Vistara Premium economy
    - Trujet
  
  Source:
    - Delhi
    - Kolkata
    - Banglore
    - Mumbai
    - Chennai

  Destination:
    - Cochin
    - Banglore
    - Delhi
    - New Delhi
    - Hyderabad
    - Kolkata
  
